import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

const Urbanist = localfont({
  src: [
    {
      path: "../../public/fonts/Urbanist-VariableFont_wght.ttf",
      weight: "500",
    },
  ],
  variable: "--urbanist",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Urbanist.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
